export const attendantUrl = "v1/api/attendances/attendant/"
export const departmentUrl = "v1/api/attendances/department/"
export const internalChatUrl = "v1/api/attendances/internal_chat/"
export const allAttendances = "v1/api/attendances/attendant/all/"
export const getInstances = "v1/api/instances/instance/"
export const statusInstances = "http://localhost:8000/v1/api/instances/status_instance/"