export const attendantUrl = "v1/api/attendances/attendant/";
export const departmentUrl = "v1/api/attendances/department/";
export const internalChatUrl = "v1/api/attendances/internal_chat/";
export const allAttendances = "v1/api/attendances/attendant/all/";
export const getInstances = "v1/api/instances/instance/";
export const stateInstance = (id) => `v1/api/instances/instance/${id}/state/`;
export const crm_scheduled = "v1/api/crm/event/scheduled_message/";
export const crm_events = "v1/api/crm/event/calendar";
export const crm_products = "v1/api/crm/products/";
export const contact_tag = "v1/api/contacts/tag/";
